apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Chart.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    routes:
      - pattern: "/api/forecast"
        method:
          - "GET"
        backend_dns: "http://forecast-back-service.pro-pokemon-weather-map-back.svc.cluster.local:8000"