namespace: pro-pokemon-weather-map-back
replicaCount: 1
registry: harbor.server.local/danielbeltejar/pokemon-weather-map
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
extraEnv:
- name: "TZ"
  value: "UTC"
extraEnvFrom: []
resources:
  requests:
    memory: "32Mi"
  limits:
    cpu: 500m
    memory: "128Mi"
volumeMounts:
  - name: images-volume
    mountPath: /app/images
volumes:
  - name: images-volume
    persistentVolumeClaim:
      claimName: images-pvc