apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "app.selectorLabels" . | nindent 12 }}
        spec:
          securityContext:
            fsGroup: 65534
          automountServiceAccountToken: false
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - {{ include "app.fullname" . }}
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: '{{ include "app.fullname" . }}-container'
              image: "{{ .Values.registry }}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- with .Values.extraEnv }}
                  {{- toYaml . | nindent 18 }}
                {{- end }}
              envFrom:
                {{- with .Values.extraEnvFrom }}
                  {{- toYaml . | nindent 18 }}
                {{- end }}
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                runAsUser: 65534
                runAsGroup: 65534
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
              {{- with .Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
          {{- with .Values.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure