apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 19 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app:  {{ .Chart.Name }}
        spec:
          securityContext:
            fsGroup: 10003
          automountServiceAccountToken: false
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - {{ .Chart.Name }}
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: {{ .Chart.Name }}-container
              image: "{{ .Values.registry }}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: Always
              env:
              {{- range $key, $val := .Values.env }}
                - name: {{ $key }}
                  value: {{ $val | quote }}
              {{- end }}
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                runAsUser: 10001
                runAsGroup: 10002
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              resources:
                requests:
                  memory: "32Mi"
                limits:
                  cpu: 500m
                  memory: "128Mi"
              volumeMounts:
                - mountPath: /app/images/output
                  name: app-volume
          volumes:
            - name: app-volume
              persistentVolumeClaim:
                claimName: pkmnwmapp-pvc
          restartPolicy: OnFailure